import { Main } from 'modules/main';
import type { NextPage } from 'next';
import Head from 'next/head';

const MainPage: NextPage = () => {
  return (
    <div className="min-h-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative w-full h-full">
        <Main />
      </main>
    </div>
  );
};

export default MainPage;
